version: v1
ingest_threads: 8
collections:
  - name: "Source Collection"
    id: "source_collection"
    mode: "overwrite"
    chunk_size: 500
    chunk_overlap: 250
    embedding_model: "all-MiniLM-L6-v2"
    metadata:
      key: "value"
    sources:
      - type: "source"
        url_fragment: "/departments"
        recursive: true
        attachments: true
        metadata:
          key: "value"
